[package]
name = "heic_to_png"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "heic_to_png"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
libheif-rs = "0.15.0"
image = "0.24.2"
